version: "3"

services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todo_db
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    hostname: postgres # コンテナのhostnameを明示的に指定
    restart: always
    stdin_open: true

  client:
    container_name: client
    image: myclient
    restart: always
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todo_db
      - WORKERS=2
    entrypoint: ["./run.sh"]
    ports:
      - 8888:8888
      - 8000:8000
    depends_on:
      - postgres
